### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ghost** [thibautd/JSerial#2]
I'm trying to run the example code and end up getting this error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Das angegebene Modul wurde nicht gefunden.

```
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
at dk.thibaut.serial.SerialPortWindows.<clinit>(SerialPortWindows.java:46)
at dk.thibaut.serial.SerialPort.open(SerialPort.java:75)
at com.siltronic.tzv.JSerialImpl.main(JSerialImpl.java:28)
```

---

I added JSerial and JNA to the classpath. Have I forgotten something?

My Code:

```
import dk.thibaut.serial.SerialChannel;
import dk.thibaut.serial.SerialPort;
import dk.thibaut.serial.enums.*;

import java.io.IOException;

import java.io.InputStream;

import java.nio.ByteBuffer;

import java.util.List;

public class JSerialImpl {
public JSerialImpl() {
    super();
}

public static void main(String[] args) throws IOException {
    JSerialImpl jSerialImpl = new JSerialImpl();

    // Get a list of available ports names (COM2, COM4, ...)
    List<String> portsNames = dk.thibaut.serial.SerialPort.getAvailablePortsNames();

    // Get a new instance of SerialPort by opening a port.
    SerialPort port = SerialPort.open("COM1");

    // Configure the connection
    port.setTimeout(100);
    port.setConfig(BaudRate.B9600, Parity.NONE, StopBits.ONE, DataBits.D8);

    // You have the choice, you can either use the Java NIO channels
    // or classic Input/Ouput streams to read and write data.
    SerialChannel channel = port.getChannel();
    InputStream istream = port.getInputStream();

    // Read some data using a stream
    byte[] byteBuffer = new byte[4096];
    // Will timeout after 100ms, returning 0 if no bytes were available.
    int n = istream.read(byteBuffer);

    // Read some data using a ByteBuffer.
    ByteBuffer buffer = ByteBuffer.allocate(4096);
    int c = channel.read(buffer);

    port.close();
    System.out.print("test");
    System.out.print(c);
}
}
```

**Comment by thibautd** [comment]
Hello, I'm sorry I totally missed you opened an issue. I said in the README, can you check that you installed the MSVC redistributable C++ 2015 ?

**Comment by thibautd** [comment]
I close this issue.
